name: Build Cork

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-15 

    steps:
      - name: Checkout Cork Repository
        uses: actions/checkout@v4
        with:
          repository: buresdv/Cork

      # We absolutely need Xcode 26.2 to get Swift 6.2+
      - name: Select Xcode 26.2
        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

      - name: Install Mise
        run: curl https://mise.run | sh

      - name: Install Tuist via Mise and Generate Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          eval "$($HOME/.local/bin/mise activate bash)"
          mise install tuist
          mise exec tuist@4.50.2 -- tuist install
          mise exec tuist@4.50.2 -- tuist generate --no-binary-cache

      # Using Archive to safely compile assets, with all necessary CI bypass flags
      - name: Archive App
        run: |
          xcodebuild clean archive \
            -workspace Cork.xcworkspace \
            -scheme "Self-Compiled" \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            SWIFT_ENABLE_EXPLICIT_MODULES=NO \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGN_STYLE="Manual" \
            -archivePath Cork.xcarchive

      - name: Zip the App Bundle
        run: |
          cd Cork.xcarchive/Products/Applications
          zip -r Cork.zip Cork.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cork-App
          path: Cork.xcarchive/Products/Applications/Cork.zip
